import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Clerk imports for App Router (official Quickstart)
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";

// Font setup remains unchanged
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// PUBLIC_INTERFACE
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Demonstration usage of Clerk auth controls with App Router */}
          <header className="flex w-full items-center justify-end p-4 min-h-12 gap-4">
            <SignedIn>
              {/* Show user menu and account when signed in */}
              <UserButton afterSignOutUrl="/signin" />
            </SignedIn>
            <SignedOut>
              {/* Show manual auth buttons for demo purposes */}
              <SignInButton mode="modal">
                <button className="px-3 py-2 rounded bg-cyan-600 text-white hover:bg-cyan-700 font-semibold transition-colors">
                  Sign In
                </button>
              </SignInButton>
              <SignUpButton mode="modal">
                <button className="px-3 py-2 rounded bg-pink-600 text-white hover:bg-pink-700 font-semibold transition-colors">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
